name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello
        run: echo "Hello, World!"

      - name: Run Bye
        run: echo "Bye Bye"